version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    restart: unless-stopped
